package edu.uagro.util;

public enum Util {

    RUTA_PROPERTIES("edu.uagro.util.params"),
    //#APLICACION SBecasCasas

    //##########################################################
    //#TABLAS
    cat_anio("cat_anio"),
    cat_archivos("cat_archivos"),
    cat_lenguaindigena("cat_lenguaindigena"),
    cat_nivelbeca("cat_nivelbeca"),
    cat_nivelbecaexterna("cat_nivelbecaexterna"),
    cat_tipoarrendador("cat_tipoarrendador"),
    cat_tipobeca("cat_tipobeca"),
    cat_tipobecaexterna("cat_tipobecaexterna"),
    cat_tipocasa("cat_tipocasa"),
    cat_tiporepresentante("cat_tiporepresentante"),
    cat_tipousuario("cat_tipousuario"),
    cat_zonas("cat_zonas"),
    tbl_archivos("tbl_archivos"),
    tbl_arrendador("tbl_arrendador"),
    tbl_arrendatario("tbl_arrendatario"),
    tbl_becario("tbl_becario"),
    tbl_becarioarchivo("tbl_becarioarchivo"),
    tbl_casaestudiante("tbl_casaestudiante"),
    tbl_detallebecaexterna("tbl_detallebecaexterna"),
    tbl_detallebecario("tbl_detallebecario"),
    tbl_expedientecasa("tbl_expedientecasa"),
    tbl_expedientecasamorador("tbl_expedientecasamorador"),
    tbl_representante("tbl_representante"),
    tbl_responsable("tbl_responsable"),
    tbl_usuarios("tbl_usuarios"),

    //##########################################################
    //#ColumnasTABLAS
    //#cat_anio
    cat_anioid("cat_anioId"),
    cat_anioNombre("cat_anioNombre"),
    //#cat_archivos
    cat_archivosId("cat_archivosId"),
    cat_archivosNombre("cat_archivosNombre"),
    cat_archivosEstado("cat_archivosEstado"),
    //#cat_lenguaindigena
    cat_lenguaindigenaId("cat_lenguaindigenaId"),
    cat_lenguaindigenaNombre("cat_lenguaindigenaNombre"),
    //#cat_nivelbeca
    cat_nivelbecaId("cat_nivelbecaId"),
    cat_nivelbecaNombre("cat_nivelbecaNombre"),
    //#cat_nivelbecaexterna
    cat_nivelbecaexternaId("cat_nivelbecaexternaId"),
    cat_nivelbecaexternaNombre("cat_nivelbecaexternaNombre"),
    //#cat_tipoarrendador
    cat_tipoarrendadorId("cat_tipoarrendadorId"),
    cat_tipoarrendadorNombre("cat_tipoarrendadorNombre"),
    //#cat_tipobeca
    cat_tipobecaId("cat_tipobecaId"),
    cat_tipobecaNombre("cat_tipobecaNombre"),
    cat_tipobecaNivelMaximo("cat_tipobecaNivelMaximo"),
    cat_tipobecaDescripcion("cat_tipobecaDescripcion"),
    //#cat_tipobecaexterna
    cat_tipobecaexternaId("cat_tipobecaexternaId"),
    cat_tipobecaexternaNombre("cat_tipobecaexternaNombre"),
    cat_tipobecaexterna_cat_nivelbecaexternaId("cat_nivelbecaexternaId"),
    cat_tipobecaexternaDescripcion("cat_tipobecaexternaDescripcion"),
    //#cat_tipocasa
    cat_tipocasaId("cat_tipocasaId"),
    cat_tipocasaNombre("cat_tipocasaNombre"),
    //#cat_tipousuario
    cat_tiporepresentanteId("cat_tiporepresentanteId"),
    cat_tiporepresentanteNombre("cat_tiporepresentanteNombre"),
    //#cat_tipousuario
    cat_tipousuarioId("cat_tipousuarioId"),
    cat_tipousuarioNombre("cat_tipousuarioNombre"),
    //#cat_zonas
    cat_zonasId("cat_zonasId"),
    cat_zonasNombre("cat_zonasNombre"),
    cat_zonasDescripcion("cat_zonasDescripcion"),
    //#tbl_archivos
    tbl_archivosId("tbl_archivosId"),
    tbl_archivos_tbl_expedientecasaId("tbl_expedientecasaId"),
    tbl_archivosNombre("tbl_archivosNombre"),
    tbl_archivosExtencion("tbl_archivosExtencion"),
    tbl_archivosURL("tbl_archivosURL"),
    tbl_archivosDescripcion("tbl_archivosDescripcion"),
    tbl_archivos_cat_archivosId("tbl_archivos_cat_archivosId"),
    //#tbl_arrendador
    tbl_arrendadorId("tbl_arrendadorId"),
    tbl_arrendadorNumProveedor("tbl_arrendadorNumProveedor"),
    tbl_arrendadorRFC("tbl_arrendadorRFC"),
    tbl_arrendadorNombre("tbl_arrendadorNombre"),
    tbl_arrendadorApellidoPat("tbl_arrendadorApellidoPat"),
    tbl_arrendadorApellidoMat("tbl_arrendadorApellidoMat"),
    tbl_arrendadorDomicilio("tbl_arrendadorDomicilio"),
    tbl_arrendadorCurp("tbl_arrendadorCurp"),
    tbl_arrendadorTelefono("tbl_arrendadorTelefono"),
    tbl_arrendadorEmail("tbl_arrendadorEmail"),
    tbl_arrendador_cat_tipoarrendadorId("cat_tipoarrendadorId"),
    //#tbl_arrendatario
    tbl_arrendatarioId("tbl_arrendatarioId"),
    tbl_arrendatarioNombre("tbl_arrendatarioNombre"),
    tbl_arrendatarioCargo("tbl_arrendatarioCargo"),
    tbl_arrendatarioDomicilio("tbl_arrendatarioDomicilio"),
    //#tbl_becario
    tbl_becarioId("tbl_becarioId"),
    tbl_becarioNombre("tbl_becarioNombre"),
    tbl_becarioApellidoPat("tbl_becarioApellidoPat"),
    tbl_becarioApellidoMat("tbl_becarioApellidoMat"),
    tbl_becarioCurp("tbl_becarioCurp"),
    tbl_becarioFechaRegistro("tbl_becarioFechaRegistro"),
    tbl_becarioEstado("tbl_becarioEstado"),
    tbl_becarioTelefono("tbl_becarioTelefono"),
    //#tbl_becarioarchivo
    tbl_becarioarchivoId("tbl_becarioarchivoId"),
    tbl_becarioarchivo_tblbecarioId("tbl_becarioId"),
    tbl_becarioarchivoNombre("tbl_becarioarchivoNombre"),
    tbl_becarioarchivoExtencion("tbl_becarioarchivoExtencion"),
    tbl_becarioarchivoURL("tbl_becarioarchivoURL"),
    tbl_becarioarchivoDescripcion("tbl_becarioarchivoDescripcion"),
    //#tbl_casaestudiante
    tbl_casaestudianteClave("tbl_casaestudianteClave"),
    tbl_casaestudianteNombre("tbl_casaestudianteNombre"),
    tbl_casaestudianteDireccion("tbl_casaestudianteDireccion"),
    tbl_casaestudianteLatitud("tbl_casaestudianteLatitud"),
    tbl_casaestudianteLongitud("tbl_casaestudianteLongitud"),
    tbl_casaestudianteObservacion("tbl_casaestudianteObservacion"),
    tbl_casaestudiante_cat_tipocasaId("cat_tipocasaId"),
    tbl_casaestudiante_cat_zonasId("cat_zonasId"),
    tbl_casaestudianteEstado("tbl_casaestudianteEstado"),
    //#tbl_detallebecaexterna
    tbl_detallebecaexternaId("tbl_detallebecaexternaId"),
    tbl_detallebecaexterna_cat_anioId("cat_anioId"),
    tbl_detallebecaexterna_cat_tipobecaexternaId("cat_tipobecaexternaId"),
    tbl_detallebecaexterna_tbl_unidadacademicaNombre("tbl_unidadacademicaNombre"),
    tbl_detallebecaexternaCantidad("tbl_detallebecaexternaCantidad"),
    tbl_detallebecaexternaEstado("tbl_detallebecaexternaEstado"),
    //#tbl_detallebecario
    tbl_detallebecarioId("tbl_detallebecarioId"),
    tbl_detallebecarioFecha("tbl_detallebecarioFecha"),
    tbl_detallebecario_tbl_becarioId("tbl_becarioId"),
    tbl_detallebecarioFechaInicioBeca("tbl_detallebecarioFechaInicioBeca"),
    tbl_detallebecarioFechaFinBeca("tbl_detallebecarioFechaFinBeca"),
    tbl_detallebecarioArea("tbl_detallebecarioArea"),
    tbl_detallebecarioSolicitante("tbl_detallebecarioSolicitante"),
    tbl_detallebecarioAdscripcion("tbl_detallebecarioAdscripcion"),
    tbl_detallebecario_cat_zonasId("cat_zonasId"),
    tbl_detallebecario_cat_nivelbecaId("cat_nivelbecaId"),
    tbl_detallebecario_cat_tipobecaId("cat_tipobecaId"),
    tbl_detallebecarioObservacion("tbl_detallebecarioObservacion"),
    tbl_detallebecarioEstado("tbl_detallebecarioEstado"),
    //#tbl_expedientecasa
    tbl_expedientecasaId("tbl_expedientecasaId"),
    tbl_expedientecasa_tbl_casaestudianteClave("tbl_expedientecasa_tbl_casaestudianteClave"),
    tbl_expedientecasa_tbl_arrendatarioId("tbl_expedientecasa_tbl_arrendatarioId"),
    tbl_expedientecasa_tbl_representanteMatricula("tbl_expedientecasa_tbl_representanteMatricula"),
    tbl_expedientecasa_tbl_arrendadorId("tbl_expedientecasa_tbl_arrendadorId"),
    tbl_expedientecasaMontoRenta("tbl_expedientecasaMontoRenta"),
    tbl_expedientecasaAumento("tbl_expedientecasaAumento"),
    tbl_expedientecasaMontoTotal("tbl_expedientecasaMontoTotal"),
    tbl_expedientecasaMontoLetra("tbl_expedientecasaMontoLetra"),
    tbl_expedientecasaTipoRenta("tbl_expedientecasaTipoRenta"),
    tbl_expedientecasaFechaRegistro("tbl_expedientecasaFechaRegistro"),
    tbl_expedientecasaFechaInicialArrendamiento("tbl_expedientecasaFechaInicialArrendamiento"),
    tbl_expedientecasaFechaFinalArrendamiento("tbl_expedientecasaFechaFinalArrendamiento"),
    tbl_expedientecasaEstado("tbl_expedientecasaEstado"),
    //#tbl_expedientecasamorador
    tbl_expedientecasamoradorId("tbl_expedientecasamoradorId"),
    tbl_expedientecasamorador_tbl_expedientecasaId("tbl_expedientecasaId"),
    tbl_expedientecasamoradorMatricula("moradorMatricula"),
    tbl_expedientecasamoradorNombre("tbl_expedientecasamoradorNombre"),
    tbl_expedientecasamoradorApellidoPat("moradorApellidoPat"),
    tbl_expedientecasamoradorApellidoMat("moradorApellidoMat"),
    tbl_expedientecasamoradorSexo("moradorSexo"),
    tbl_expedientecasamoradorUAcademica("moradorUAcademica"),
    tbl_expedientecasamoradorGrado("moradorGrado"),
    tbl_expedientecasamoradorTurno("moradorTurno"),
    tbl_expedientecasamoradorPromedio("moradorPromdedio"),
    tbl_expedientecasamoradorEdad("moradorEdad"),
    tbl_expedientecasamoradorMunicipio("moradorMunicipio"),
    tbl_expedientecasamoradorRegion("moradorRegion"),
    tbl_expedientecasamoradorPlanEstudio("moradorPlanEstudio"),
    tbl_expedientecasamoradorHablaLenguaIndigena("moradorHablaLenguaIndigena"),
    tbl_expedientecasamorador_cat_lenguaindigenaId("cat_lenguaindigenaId"),
    tbl_expedientecasamoradorFoto("moradorFoto"),
    tbl_expedientecasamoradorStatus("moradorStatus"),
    tbl_expedientecasamoradorObservacion("moradorObservacion"),
    //#tbl_representante
    tbl_representanteMatricula("tbl_representanteMatricula"),
    tbl_representanteNombre("tbl_representanteNombre"),
    tbl_representanteApellidoPat("tbl_representanteApellidoPat"),
    tbl_representanteApellidoMat("tbl_representanteApellidoMat"),
    tbl_representanteSexo("tbl_representanteSexo"),
    tbl_representanteEstadoCivil("tbl_representanteEstadoCivil"),
    tbl_representanteFechaRegistro("tbl_representanteFechaRegistro"),
    tbl_representanteFechaNacimiento("tbl_representanteFechaNacimiento"),
    tbl_representanteCurp("tbl_representanteCurp"),
    tbl_representanteEstadoNacimiento("tbl_representanteEstadoNacimiento"),
    tbl_representanteMunicipioNacimiento("tbl_representanteMunicipioNacimiento"),
    tbl_representanteUAcademica("tbl_representanteUAcademica"),
    tbl_representanteSemestre("tbl_representanteSemestre"),
    tbl_representanteGrado("tbl_representanteGrado"),
    tbl_representanteTurno("tbl_representanteTurno"),
    tbl_representantePromedio("tbl_representantePromedio"),
    tbl_representanteTelefono("tbl_representanteTelefono"),
    tbl_representanteEmail("tbl_representanteEmail"),
    tbl_representanteClave("tbl_representanteClave"),
    tbl_representanteEstado("tbl_representanteEstado"),
    tbl_representante_cat_tiporepresentanteId("cat_tiporepresentanteId"),
    //#tbl_responsable
    tbl_responsableId("tbl_responsableId"),
    tbl_responsableNombre("tbl_responsableNombre"),
    tbl_responsableApellidoPat("tbl_responsableApellidoPat"),
    tbl_responsableApellidoMat("tbl_responsableApellidoMat"),
    tbl_responsableEmail("tbl_responsableEmail"),
    tbl_responsable_cat_zonasId("cat_zonasId"),
    tbl_responsableEstado("tbl_responsableEstado"),
    //#tbl_usuarios
    tbl_usuariosId("tbl_usuariosId"),
    tbl_usuarios_cat_tipousuarioId("cat_tipousuarioId"),
    tbl_usuariosNombre("tbl_usuariosNombre"),
    tbl_usuariosEmail("tbl_usuariosEmail"),
    tbl_usuariosContrasenia("tbl_usuariosContrasenia"),
    tbl_usuariosEstado("tbl_usuariosEstado"),
    tbl_usuariosFechaCreacion("tbl_usuariosFechaCreacion"),
    //############################################################
    //#OPERADORES SQL
    ESPACIO_IGUAL_ESPACIO("ESPACIO_IGUAL_ESPACIO"),
    WHERE("WHERE"),
    FROM("FROM"),
    INSERT_INTO("INSERT_INTO"),
    UPDATE("UPDATE"),
    SET("SET"),
    SELECT("SELECT"),
    DELETE_FROM("DELETE_FROM"),
    AND("AND"),
    UNION("UNION"),
    INNER_JOIN("INNER_JOIN"),
    LEFT_JOIN("LEFT_JOIN"),
    ON("ON"),
    ORDER_BY("ORDER_BY"),
    OR("OR"),
    GROUP("GROUP_BY"),
    SUMA("SUMA"),
    VALUES("VALUES"),
    LIKE("LIKE"),
    BETWEEN("BETWEEN"),
    TO_DATE("TO_DATE"),
    SYSDATE("SYSDATE"),
    ASTERISCO("ASTERISCO"),
    PUNTO("PUNTO"),
    QUESTION_MARK("QUESTION_MARK"),
    GT("GT"),
    LT("LT"),
    INITCAP("INITCAP"),
    UPPER("UPPER"),
    LOWER("LOWER"),
    ASC("ASC"),
    DESC("DESC"),
    NEXTVAL("NEXTVAL"),
    //#####################################################
    //#APLICACION
    COMILLA_COMA_COMILLA("COMILLA_COMA_COMILLA"),
    COMA_COMILLA("COMA_COMILLA"),
    COMILLA_COMA("COMILLA_COMA"),
    COMA("COMA"),
    OPEN_PARANTESIS("OPEN_PARANTESIS"),
    CLOSE_PARANTESIS("CLOSE_PARANTESIS"),
    ESPACIO("ESPACIO"),
    COMILLA("COMILLA"),
    FORMATO_FECHA("FORMATO_FECHA"),
    FORMATO_FECHA_DD_MM_RRRR("FORMATO_FECHA_DD_MM_RRRR"),
    //#ENCRIPTACION Y DESCRIPTACION
    SEMILLA("SEMILLA"),
    UTF8("UTF8"),
    ALGORITMO_CIFRADO("ALGORITMO_CIFRADO"),
    TAMANO_PASSWORD("TAMANO_PASSWORD"),
    //#ESTADO DE REGISTROS
    ACTIVO("ACTIVO"),
    INACTIVO("INACTIVO"),
    ESTADO_FALSE("ESTADO_FALSE"),
    ESTADO_TRUE("ESTADO_TRUE");

    private String propiedad;

    private Util(String propiedad) {
        this.setPropiedad(propiedad);
    }

    public String getPropiedad() {
        return propiedad;
    }

    public void setPropiedad(String propiedad) {
        this.propiedad = propiedad;
    }

//    public static void main(String[] args) {
//        System.out.println(Util.CostoPromedioAlumno_ciclofin.getPropiedad());
//    }
}
